### ISSUE TITLE
Consider connecting to the ultra sound relay

### ISSUE THREAD

**Issue by JustinDrake** [zeus-fyi/zeus#123]
Consider connecting to a non-censoring relay, e.g. `https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`

https://github.com/zeus-fyi/zeus/blob/03cb9cff2a2bc372d23c9ad665f0380c6a837eb5/cookbooks/ethereum/mev/mev_relays.go#L6-L10

**Comment by ctrl-alt-lulz** [comment]
@JustinDrake if you create a pr I'll merge it for you

**Comment by JustinDrake** [comment]
Done! :) https://github.com/zeus-fyi/zeus/pull/174

**Comment by ctrl-alt-lulz** [comment]
merged!
